Action2theFuture/Minishell

Makefile
includes/minishell.h
libft/src/ft_strndup.c
src/built_in/built_in.c
src/built_in/file_dir_operations.c
src/built_in/ft_cd.c
src/built_in/ft_echo.c
src/built_in/ft_env.c
src/built_in/ft_exit.c
src/built_in/ft_export.c
src/built_in/ft_pwd.c
src/built_in/ft_unset.c
src/exec/cmd.c
src/init/env_init.c
src/utils/string_utils_2.c

built_in init

---

includes/minishell.h
src/init/env_init.c
src/utils/string_utils_2.c

- Add : Functions to remove double or single quotes at both ends

Add : Functions to remove double or single quotes at both ends

---

src/exec/execute_process.c
src/exec/redir.c
src/process_input.c

- Fix : commands going through despite failed redirects

Fix : commands going through despite failed redirects

---

src/exec/utils/args_utils.c
src/exec/utils/handler_replace_env_vars.c
src/exec/utils/var_expansion_with_args.c

…expansion
- Fix : Memory leak from itoa
- Add : limit of cnt's argument in env expansion

Fix : Memory leak from itoa and Add : limit of cnt's argument in env expansion

---

src/process_input.c

Modify : remove printf

---

.gitignore
Makefile

Modify : gitingore and Makefile

---

src/parsing/arg_parse.c

- Fix : bug from arg parsing of flag

Fix : bug from arg parsing of flag

---

includes/minishell.h

Fix : norminette in minishell.h

---

Makefile

- Fix : headerfile and Makefile

Fix : headerfile and Makefile

---

Makefile
src/built_in/utils/handle_pwd_oldpwd.c
src/exec/utils/args_utils.c
src/exec/utils/expansion_and_quotes/expand_wildcard.c
src/exec/utils/expansion_and_quotes/expand_wildcard_utils.c
src/init/env_init.c
src/init/env_utils.c

- Fix : memory leak from cd and expansion wiildcard

Fix : memory leak from cd and expansion wiildcard

---

Makefile
includes/minishell.h
src/init/env_init.c
src/init/env_utils_2.c

- Modify : add_env functions name

Modify : add_env functions name

---

src/init/env_utils.c

- Modify : put duplicate env variables in env

Modify : put duplicate env variables in env

---

src/built_in/ft_cd.c

Fix : name

---

includes/minishell_types.h

- Modify : change ARR_SEP from ';' to '`'

Modify : change ARR_SEP from ';' to '`'

---

Makefile
includes/execute.h
includes/minishell.h
includes/minishell_types.h
src/exec/dispatch_cmd.c
src/exec/utils/expansion_and_quotes/handler_replace_env_vars.c
src/exec/utils/expansion_and_quotes/handler_replace_env_vars_without_quotes.c
src/exec/utils/expansion_and_quotes/handler_under_score.c
src/exec/utils/expansion_and_quotes/replace_env_vars_utils_2.c
src/init/env_init.c
src/init/env_utils.c
src/init/env_utils_2.c

- Add : expansion variables by under score

Add : expansion variables by under score

---

src/exec/utils/expansion_and_quotes/handler_replace_env_vars.c
src/exec/utils/expansion_and_quotes/handler_under_score.c
src/exec/utils/expansion_and_quotes/replace_env_vars_utils_2.c
src/exec/utils/expansion_and_quotes/var_expansion_with_args.c
src/init/env_utils_2.c

Please enter the commit message for your changes. Lines starting
- Fix : memory leak and uninitialized value from expansion of under score

Fix : memory leak and uninitialized value from expansion of under score

---

src/exec/utils/fd_utils.c
src/exec/utils/info_utils.c

Modify : location of close(info->fd_null)

---

src/minishell.c

Remove : input break in shell loop

---

src/exec/process_execute.c

- Fix : Allocate NULL pointer after free info->redir_arg memory

Fix : Allocate NULL pointer after free info->redir_arg memory

---

src/parsing/tokenize/handle_quotes.c
src/parsing/tokenize/handler_operators_and_spaces.c

- Fix : token handling (echo helloworld -> hello orld)

Fix : token handling (echo helloworld -> hello orld)

---

Makefile
includes/minishell.h
includes/minishell_types.h
src/exec/process_redir.c
src/exec/utils/here_doc.c
src/signal/handler_heredoc_signal.c

- Add : global var for exiting heredoc with interrupt key

Add : global var for exiting heredoc with interrupt key

---

Makefile
includes/execute.h
src/exec/process_execute.c
src/exec/process_execute_pipe.c
src/exec/process_redir.c
src/exec/utils/fd_utils.c
src/exec/utils/here_doc.c
src/exec/utils/redirect_to_null.c
src/signal/handler_heredoc_signal.c

and changed from readline to gnl with working herdoc Add : reset standard input when receiving the last redirecttion
Organaize : makefile and execute files
- Modify : remove newline while putting input with heredoc and changed from readline to gnl with working herdoc
- Add : reset standard input when receiving the last redirecttion
- Organaize : makefile and execute files
- The function logic seems to be too long, I wonder …

Modify : overall heredoc and Organize : Makefile and execute files

---

src/parsing/tokenize/handler_operators_and_spaces.c

- Add : condition(cnt > 1) in handle_repqeated_operators

Add : condition(cnt > 1) in handle_repqeated_operators

---

src/exec/process_execute_pipe.c

- Add : exit code after terminating subshell with only cmd

Add : exit code after terminating subshell with only cmd

---

src/built_in/utils/ft_export_utils.c
src/exec/subshell.c

…anup_and_exit in subshell
- Fix : var if exist funtion in export and Modify : change location cleanup_and_exit in subshell

Fix : var if exist funtion in export and Modify : change location cleanup_and_exit in subshell

---

includes/execute.h
includes/minishell_types.h
src/exec/process_execute.c
src/exec/process_redir.c
src/exec/redir.c
src/exec/utils/fd_utils.c
src/exec/utils/here_doc.c
src/exec/utils/init_info.c
src/exec/utils/redirect_to_null.c

- Fix : print cat next to heredoc in pipeline
- Add : to heredoc that does not apply to extended environment variables

Fix : bugs from heredoc and Add : to heredoc that does not apply to extended environment variables

---

src/init/env_init.c

…lize_default_env
- Modify : changed location between add_env_minimum_required and initialize_default_env

 Modify : changed location between add_env_minimum_required and initialize_default_env

---

src/built_in/utils/builtin_node_utils.c
src/exec/execute.c

- Fix : update variable export
- Add : to make subshells behave like trailing logic

Add : to make subshells behave like trailing logic Fix : update variable export

---

src/exec/execute.c

Fix : mistake

---

src/exec/subshell.c

- Fix : still memory leak consecutively nested subshell more than 2

Fix : still memory leak consecutively nested subshell more than 2

---

Makefile
includes/execute.h
src/exec/nested_subshell.c
src/exec/subshell.c

…emory leak from pipeline in nested subshell
- Organize : func to handle nested subshell
- Fix : still reachable memory leak from pipeline in nested subshell

Organize : func to handle nested subshell and Fix : still reachable memory leak from pipeline in nested subshell

---

src/exec/utils/here_doc.c

Add : heredoc limiter parse to remove quote
